### PR TITLE
eth_getProof balance and nonce to U256

### PR DESCRIPTION
**Pull request by lightyear15**
after some real-world testing, we figured balance as well as nonce
fields might reach the upper limit of U64.
Moving these fields to U256

### CODE REVIEW

**Comment by lightyear15** [comment]
sorry about this :disappointed: 
should have then more tests before my first PR

**Comment by tomusdrw** [comment]
No worries! Could you please add a testcase for these large values as well?

**Comment by lightyear15** [comment]
Hi @tomusdrw 
I changed the unit test as you requested. 
The proof does not need to be consistent as that is not the purpose of the test. So I just changed the value of ``balance`` and ``nonce`` fields to make them more similar to a real-case.

**Comment by tomusdrw** [comment]
Perfect, thank you!

**Review by tomusdrw — APPROVED** [review]

**Pull request merged**
