### PR TITLE
Use rustfmt to format crate

### PR DESCRIPTION
**Pull request by mjkoo**
As discussed in #92 , adds `rustfmt.toml` and adds `cargo fmt` as a step in travis, addresses #92 and #12 

Recommend holding off until other PRs are merged.

### CODE REVIEW

**Comment by mjkoo** [comment]
Seems like stable rustfmt disagrees with beta/nightly...

**Comment by tomusdrw** [comment]
@mjkoo do you mind reformatting again?

**Comment by mjkoo** [comment]
Rebased off of current master and reformatted

@tomusdrw perhaps it makes more sense to grab the first 2 commits and `cargo fmt` it yourself?
 If reviewing this large diff is the barrier to getting this merged that is.

**Comment by tomusdrw** [comment]
Sorry @mjkoo, forgot about the PR. Thanks again!

**Pull request merged**
