### PR TITLE
Implemented kill_account and new_account_from_phrase of parity_Accounts API.

### PR DESCRIPTION
**Pull request by CPerezz**
Here i leave the traces: 

**Just one thing to mention.**

During the test. The account that Parity Node imported from the seed: `member funny cloth wrist ugly water tuition always fall recycle maze long` was: `0x00172b1ac860176736be6ecd9cb63f7ffd663815`. 
**But on Metamask, the 1st account derivated from the seed corresponds to: `0xE43eD16390bd419d48B09d6E2aa20203D1eF93E1`.** 

That drives me to think that the dictionary used by the Parity node or the KDF differ in some values from Metamask one's. What do you think??

If i can help with something, just tell me!

### CODE REVIEW

**Comment by tomusdrw** [comment]
@CPerezz Parity Brain Wallet used to use a different key-derivation algorithm (https://github.com/ethereum/wiki/wiki/Brain-Wallet) I think metamask uses standard BIP39 derivation hence the difference.

**Comment by CPerezz** [comment]
Wow! Perfect!! I thougth about the diferent KDF but didn't knew the Brain-Wallet implementation. Thanks for sharing! I'll read about it. Any differences or improvements over the standard Bip39?

And you're right, Metamask uses the standard BIP39 algorithm.

Thanks @tomusdrw !

**Comment by tomusdrw** [comment]
@CPerezz thanks again for the contribution!

**Comment by tomusdrw** [comment]
The `00` is there to make the address shorter I think. Yeah, BIP39 would be nice although we phase out account management from the main node anyway so it should go to its own crate (possibly `ethkey`)

**Pull request merged**
