### PR TITLE
Convert transaction signing to `async`

### PR DESCRIPTION
**Pull request by e00E**
Converting the manual Future implementation to async makes the code
simpler and no longer require Unpin.

part of  #361

### CODE REVIEW

**Review by tomusdrw — APPROVED** [review]
That's amazing :heart_eyes:, thank you so much!

**Comment by e00E** [comment]
Are you sure you want to bump version immediately? To be clear, this code does not yet have outside observable effect but it is a part of several changes that will be required to remove Unpin.

**Comment by tomusdrw** [comment]
> Are you sure you want to bump version immediately?

Bumping the version, just so that I don't forget to do it later on. Different return types is a breaking change already, so I'd prefer to indicate that the git version is different than what's on crates.io. Totally fine with merging more changes before the actual release.

**Comment by e00E** [comment]
Makes sense :+1:

**Pull request merged**
