### PR TITLE
Upgrade to tokio 1.0

### PR DESCRIPTION
**Pull request by e00E**
Closes https://github.com/tomusdrw/rust-web3/issues/445

This should not be merged yet because there are two git dependencies. For both crates I have created PRs to update them to tokio 1.0 but they have not been merged yet:
* https://github.com/tafia/hyper-proxy/pull/18
* https://github.com/async-email/async-native-tls/pull/25

### CODE REVIEW

**Comment by tomusdrw** [comment]
Awesome!

**Comment by wesrer** [comment]
Could we potentially switch over to https://github.com/Azure/hyper-proxy instead

**Comment by wesrer** [comment]
Both these libraries have updated to tokio 1.0 as of today, I believe. @tomusdrw @e00E is this ready to be merged yet?

**Comment by e00E** [comment]
They have updated but haven't had a release to crates.io yet, so we still have to wait:
* https://crates.io/crates/hyper-proxy
* https://crates.io/crates/async-native-tls

**Comment by toxeus** [comment]
:heavy_check_mark: `hyper-proxy` had a new release recently
:hourglass_flowing_sand: `async-native-tls` is still pending

**Comment by tomusdrw** [comment]
@e00E do you mind rebasing the PR? I'm considering merging this even with `async-native-tls` being a git dependency for now.

**Comment by e00E** [comment]
Done. Btw you won't be able to make a crates.io release with a git dependency.

**Review by tomusdrw — APPROVED** [review]
Thanks!

**Pull request merged**
