### PR TITLE
Replace `JsValue::into/from_serde` with `serde-wasm-bindgen`

### PR DESCRIPTION
**Pull request by sergeyboyko0791**
`wasm-bindgen::serde-serialize` feature may lead to a cyclic package dependency like
```
error: cyclic package dependency: package `wasm-bindgen v0.2.74` depends on itself. Cycle:
package `wasm-bindgen v0.2.74`
    ... which is depended on by `js-sys v0.3.51`
    ... which is depended on by `getrandom v0.2.2`
    ... which is depended on by `ahash v0.7.4`
    ... which is depended on by `hashbrown v0.11.2`
    ... which is depended on by `indexmap v1.7.0`
    ... which is depended on by `serde_json v1.0.57`
    ... which is depended on by `wasm-bindgen v0.2.74`
    ... which is depended on by `getrandom v0.1.14`
    ... which is depended on by `const-random-macro v0.1.8`
    ... which is depended on by `const-random v0.1.8`
    ... which is depended on by `ahash v0.2.18`
```

Due to this problem, `JsValue::into_serde` and `JsValue::from_serde` were deprecated at https://github.com/rustwasm/wasm-bindgen/pull/3031

Motivation: https://github.com/KomodoPlatform/atomicDEX-API/issues/1042#issuecomment-1348375886

### CODE REVIEW

**Comment by sergeyboyko0791** [comment]
`serde-wasm-bindgen` likely doesn't handle `serde(deny_unknown_fields)` attribute properly. Will try to find a workaround.

**Comment by sergeyboyko0791** [comment]
I had to disable `serde(deny_unknown_fields)` due to https://github.com/cloudflare/serde-wasm-bindgen/issues/39

**Comment by sergeyboyko0791** [comment]
As a workaround I can follow this advice https://github.com/cloudflare/serde-wasm-bindgen/issues/39#issuecomment-1372332074
Please let me know if it's critical to deny unknown fields.

**Review by tomusdrw — APPROVED** [review]
`deny_unknown_fields` was kind of inherited from `jsonrpc_core` while solving #544.
I like it, but for no particular practical reason, just an ocd. But getting rid of a deprecation warning is way more important, so thank you for the PR!

**Pull request merged**
